//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R6Randomizer_1._0._0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked2 {
            get {
                return ((bool)(this["boxChecked2"]));
            }
            set {
                this["boxChecked2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked3 {
            get {
                return ((bool)(this["boxChecked3"]));
            }
            set {
                this["boxChecked3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked4 {
            get {
                return ((bool)(this["boxChecked4"]));
            }
            set {
                this["boxChecked4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked5 {
            get {
                return ((bool)(this["boxChecked5"]));
            }
            set {
                this["boxChecked5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked6 {
            get {
                return ((bool)(this["boxChecked6"]));
            }
            set {
                this["boxChecked6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked7 {
            get {
                return ((bool)(this["boxChecked7"]));
            }
            set {
                this["boxChecked7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked8 {
            get {
                return ((bool)(this["boxChecked8"]));
            }
            set {
                this["boxChecked8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked9 {
            get {
                return ((bool)(this["boxChecked9"]));
            }
            set {
                this["boxChecked9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked10 {
            get {
                return ((bool)(this["boxChecked10"]));
            }
            set {
                this["boxChecked10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked11 {
            get {
                return ((bool)(this["boxChecked11"]));
            }
            set {
                this["boxChecked11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked12 {
            get {
                return ((bool)(this["boxChecked12"]));
            }
            set {
                this["boxChecked12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked13 {
            get {
                return ((bool)(this["boxChecked13"]));
            }
            set {
                this["boxChecked13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked14 {
            get {
                return ((bool)(this["boxChecked14"]));
            }
            set {
                this["boxChecked14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked15 {
            get {
                return ((bool)(this["boxChecked15"]));
            }
            set {
                this["boxChecked15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked16 {
            get {
                return ((bool)(this["boxChecked16"]));
            }
            set {
                this["boxChecked16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked17 {
            get {
                return ((bool)(this["boxChecked17"]));
            }
            set {
                this["boxChecked17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked18 {
            get {
                return ((bool)(this["boxChecked18"]));
            }
            set {
                this["boxChecked18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked19 {
            get {
                return ((bool)(this["boxChecked19"]));
            }
            set {
                this["boxChecked19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked20 {
            get {
                return ((bool)(this["boxChecked20"]));
            }
            set {
                this["boxChecked20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked21 {
            get {
                return ((bool)(this["boxChecked21"]));
            }
            set {
                this["boxChecked21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked22 {
            get {
                return ((bool)(this["boxChecked22"]));
            }
            set {
                this["boxChecked22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked23 {
            get {
                return ((bool)(this["boxChecked23"]));
            }
            set {
                this["boxChecked23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked24 {
            get {
                return ((bool)(this["boxChecked24"]));
            }
            set {
                this["boxChecked24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked25 {
            get {
                return ((bool)(this["boxChecked25"]));
            }
            set {
                this["boxChecked25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked26 {
            get {
                return ((bool)(this["boxChecked26"]));
            }
            set {
                this["boxChecked26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked27 {
            get {
                return ((bool)(this["boxChecked27"]));
            }
            set {
                this["boxChecked27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked28 {
            get {
                return ((bool)(this["boxChecked28"]));
            }
            set {
                this["boxChecked28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked29 {
            get {
                return ((bool)(this["boxChecked29"]));
            }
            set {
                this["boxChecked29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked30 {
            get {
                return ((bool)(this["boxChecked30"]));
            }
            set {
                this["boxChecked30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked31 {
            get {
                return ((bool)(this["boxChecked31"]));
            }
            set {
                this["boxChecked31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked32 {
            get {
                return ((bool)(this["boxChecked32"]));
            }
            set {
                this["boxChecked32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked33 {
            get {
                return ((bool)(this["boxChecked33"]));
            }
            set {
                this["boxChecked33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked34 {
            get {
                return ((bool)(this["boxChecked34"]));
            }
            set {
                this["boxChecked34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked35 {
            get {
                return ((bool)(this["boxChecked35"]));
            }
            set {
                this["boxChecked35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked36 {
            get {
                return ((bool)(this["boxChecked36"]));
            }
            set {
                this["boxChecked36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boxChecked1 {
            get {
                return ((bool)(this["boxChecked1"]));
            }
            set {
                this["boxChecked1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked1 {
            get {
                return ((bool)(this["box2Checked1"]));
            }
            set {
                this["box2Checked1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked2 {
            get {
                return ((bool)(this["box2Checked2"]));
            }
            set {
                this["box2Checked2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked3 {
            get {
                return ((bool)(this["box2Checked3"]));
            }
            set {
                this["box2Checked3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked4 {
            get {
                return ((bool)(this["box2Checked4"]));
            }
            set {
                this["box2Checked4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked5 {
            get {
                return ((bool)(this["box2Checked5"]));
            }
            set {
                this["box2Checked5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked6 {
            get {
                return ((bool)(this["box2Checked6"]));
            }
            set {
                this["box2Checked6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked7 {
            get {
                return ((bool)(this["box2Checked7"]));
            }
            set {
                this["box2Checked7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked8 {
            get {
                return ((bool)(this["box2Checked8"]));
            }
            set {
                this["box2Checked8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked9 {
            get {
                return ((bool)(this["box2Checked9"]));
            }
            set {
                this["box2Checked9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked10 {
            get {
                return ((bool)(this["box2Checked10"]));
            }
            set {
                this["box2Checked10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked11 {
            get {
                return ((bool)(this["box2Checked11"]));
            }
            set {
                this["box2Checked11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked12 {
            get {
                return ((bool)(this["box2Checked12"]));
            }
            set {
                this["box2Checked12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked13 {
            get {
                return ((bool)(this["box2Checked13"]));
            }
            set {
                this["box2Checked13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked14 {
            get {
                return ((bool)(this["box2Checked14"]));
            }
            set {
                this["box2Checked14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked15 {
            get {
                return ((bool)(this["box2Checked15"]));
            }
            set {
                this["box2Checked15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked16 {
            get {
                return ((bool)(this["box2Checked16"]));
            }
            set {
                this["box2Checked16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked17 {
            get {
                return ((bool)(this["box2Checked17"]));
            }
            set {
                this["box2Checked17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked18 {
            get {
                return ((bool)(this["box2Checked18"]));
            }
            set {
                this["box2Checked18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked19 {
            get {
                return ((bool)(this["box2Checked19"]));
            }
            set {
                this["box2Checked19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked20 {
            get {
                return ((bool)(this["box2Checked20"]));
            }
            set {
                this["box2Checked20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked21 {
            get {
                return ((bool)(this["box2Checked21"]));
            }
            set {
                this["box2Checked21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked22 {
            get {
                return ((bool)(this["box2Checked22"]));
            }
            set {
                this["box2Checked22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked23 {
            get {
                return ((bool)(this["box2Checked23"]));
            }
            set {
                this["box2Checked23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked24 {
            get {
                return ((bool)(this["box2Checked24"]));
            }
            set {
                this["box2Checked24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked25 {
            get {
                return ((bool)(this["box2Checked25"]));
            }
            set {
                this["box2Checked25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked26 {
            get {
                return ((bool)(this["box2Checked26"]));
            }
            set {
                this["box2Checked26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked27 {
            get {
                return ((bool)(this["box2Checked27"]));
            }
            set {
                this["box2Checked27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked28 {
            get {
                return ((bool)(this["box2Checked28"]));
            }
            set {
                this["box2Checked28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked29 {
            get {
                return ((bool)(this["box2Checked29"]));
            }
            set {
                this["box2Checked29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked30 {
            get {
                return ((bool)(this["box2Checked30"]));
            }
            set {
                this["box2Checked30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked31 {
            get {
                return ((bool)(this["box2Checked31"]));
            }
            set {
                this["box2Checked31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked32 {
            get {
                return ((bool)(this["box2Checked32"]));
            }
            set {
                this["box2Checked32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked33 {
            get {
                return ((bool)(this["box2Checked33"]));
            }
            set {
                this["box2Checked33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked34 {
            get {
                return ((bool)(this["box2Checked34"]));
            }
            set {
                this["box2Checked34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked35 {
            get {
                return ((bool)(this["box2Checked35"]));
            }
            set {
                this["box2Checked35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool box2Checked36 {
            get {
                return ((bool)(this["box2Checked36"]));
            }
            set {
                this["box2Checked36"] = value;
            }
        }
    }
}
